apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cdpipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cdpipelines
  template:
    metadata:
      labels:
        app: ci-cdpipelines
    spec:
      containers:
        - name: ci-cd-pipeline
          image: aravindrio7/ci-cdpipelines:latest
          ports:
            - containerPort: 80
